apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    app: widgetario
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    component: products-api
  type: ClusterIP