apiVersion: v1
kind: Service
metadata:
  name: web-lb
  labels:
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    component: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-np
  labels:
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30080
  selector:
    component: web
  type: NodePort