apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db port=5432 user=postgres password=m*lestone3 dbname=postgres sslmode=disable"
