apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  labels:
    app: widgetario
spec:
  selector:
    matchLabels:
        app: widgetario
        component: products-db
  template:
    metadata:
      labels: 
        app: widgetario
        component: products-db
    spec:
      containers:
        - name: app
          image: widgetario/products-db:21.03
          envFrom:
            - secretRef:
                name: products-db-password