apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: widgetario
spec:
  selector:
    matchLabels:
        app: widgetario
        component: web
  template:
    metadata:
      labels: 
        app: widgetario
        component: web
    spec:
      containers:
        - name: app
          image: widgetario/web:21.03
          env:
            - name: Widgetario__Theme
              value: dark
          volumeMounts:
            - name: logging-config
              mountPath: "/app/config"
              readOnly: true
            - name: api-config
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: logging-config
          configMap:
            name: web-logging
        - name: api-config
          secret:
            secretName: web-api