apiVersion: v1
kind: Service
metadata:
  name: products-api # external Services can also be used by Pods with this DNS name
  labels:
    app: widgetario # you should have one label to identify the application
spec:
  ports:
    - port: 80 # this is the port the Service listens on
      # targetPort: 5432 # this is the target port
  selector:
    # you need a label selector which uniquely identifies the component
    component: products-api # - it should match only one Pod
    # app: products-api
  type: ClusterIP 
  # LoadBalancer means the Service can be accessed from outside Kubernetes
  # In the cloud you'll get a public IP address for the Service
  # On Docker Desktop you'll use the localhost address
  # On k3s you'll get a private IP address on your network
  # Other Kubernetes environments may not support LoadBalancer 
  # - in that case use NodePort instead and specify the nodePort in the port list