apiVersion: v1
kind: Secret
metadata:
  name: web-api
  labels:
    app: widgetario
type: Opaque
stringData:
  api.json: |-
    {
      "Widgetario": {
        "ProductsApi": {
          "Url": "http://products-api/products"
        },
        "StockApi": {
          "Url": "http://stock-api:8080/stock"
        }
      }
    }
