apiVersion: v1
kind: Secret
metadata:
  name: products-api-db-v3
type: Opaque
stringData:
  application.properties: |-
    spring.jpa.database=POSTGRESQL
    spring.jpa.generate-ddl=false
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://products-db-1.products-db.default.svc.cluster.local:5432,products-db-2.products-db.default.svc.cluster.local:5432/postgres?loadBalanceHosts=true
    spring.datasource.username=postgres
    spring.datasource.password=m*lestone3