apiVersion: v1
kind: Pod
metadata:
  name: products-api # name of the Pod - you'll use this to manage the component
  labels:
    app: widgetario # you should have one label to identify the application,
    component: products-api # and another one to identify this specific component
spec:
  containers:
    - name: app # the name of the container - not too important at this stage
      image: widgetario/products-api:21.03 # the Docker image to run - this is the full reference with the tag
      volumeMounts:
        - name: app-properties
          mountPath: "app/config"
        - name: db-properties
          mountPath: "app/config/db"
          readOnly: true
  volumes:
    - name: app-properties
      configMap:
        name: products-api-properties
    - name: db-properties
      secret:
        secretName: products-api-db