apiVersion: v1
kind: ConfigMap
metadata:
  name: products-api-properties # name referred to in the Pod spec
data:
  application.properties: |-
    price.factor=1.5
    logging.level.wiredbrain.products=DEBUG
    server.port=80
    spring.jpa.show-sql=true
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
