apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    app: widgetario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: widgetario
      component: stock-api
  template:
    metadata:
      labels:
        app: widgetario
        component: stock-api
    spec:
      containers:
        - name: app # the name of the container - not too important at this stage
          image: widgetario/stock-api:21.03 # the Docker image to run - this is the full reference with the tag
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 20
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 60
            initialDelaySeconds: 10        
          envFrom:
            - secretRef:
                name: stock-api-connection