apiVersion: v1
kind: Pod
metadata:
  name: products-db
  labels: 
    app: widgetario
    component: products-db
spec:
  containers:
    - name: app
      image: widgetario/products-db:21.03
      envFrom:
        - secretRef:
            name: products-db-password