apiVersion: v1
kind: Pod
metadata:
  name: stock-api
  labels: 
    app: widgetario
    component: stock-api
spec:
  containers:
    - name: app
      image: widgetario/stock-api:21.03
      envFrom:
        - secretRef:
            name: stock-api-connection