apiVersion: v1
kind: Pod
metadata:
  name: web # name of the Pod - you'll use this to manage the component
  labels:
    app: widgetario # you should have one label to identify the application,
    component: web # and another one to identify this specific component
spec:
  containers:
    - name: app # the name of the container - not too important at this stage
      image: widgetario/web:21.03 # the Docker image to run - this is the full reference with the tag
      envFrom:
        - configMapRef:
            name: web-features
      volumeMounts:
        - name: logging-config
          mountPath: "/app/config"
          readOnly: true
        - name: api-config
          mountPath: "/app/secrets"
          readOnly: true
  volumes:
  # volumes are like storage units attached to the Pod -
  # they're not seen by the container unless explicitly mounted
    - name: logging-config
      configMap:
        name: web-logging
    - name: api-config
      secret:
        secretName: web-api