apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection-v2
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db-0.products-db.default.svc.cluster.local port=5432 user=postgres password=m*lestone3 dbname=postgres sslmode=disable"