apiVersion: v1
kind: Service
metadata:
  name: stock-api
  labels:
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: stock-api
  type: ClusterIP