apiVersion: v1
kind: Secret
metadata:
  name: products-db-password
  labels:
    app: widgetario
type: Opaque
# Kubernetes supports different types of secret - like TLS certificates
# and Docker registry credentials. "Opaque" means the Secret isn't a 
# well-known format and doesn't get special handling.
stringData:
  POSTGRES_PASSWORD: asdj3jbcasjd
  # add more value here in the same format
  # using "stringData" means the secret is in plain text in the YAML
  # alternatively you can use base-64 encoded strings
